require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AgendasController do

  # This should return the minimal set of attributes required to create a valid
  # Table. As you add validations to Table, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TablesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    mock_morph_agendas_table
    mock_morph_district_weeks
  end

  describe "GET index" do
    xit "assigns all tables as @agendas" do
      get :index, locale: 'es'
      assigns(:agendas).should be_an_instance_of(TableCollection)
      assigns(:agendas).tables.length.should equal(2)
      assigns(:agendas).tables[0].initial_chamber.should eq('Senadores') # FIX we need to discuss about how to test the values in the response
    end
  end

  describe "GET agendas_table" do
    xit "obtains the agendas table" do
      controller = AgendasController.new
      agendas = controller.instance_eval{ agendas_table }
      agendas.first["title"].should eq 'Tabla de sesión, legislatura 361 sesión nro. 91 (Senado)'
      agendas.first["start"].should eq '2014-03-04'
      agendas.first["backgroundColor"].should eq '#a6a691'
      agendas.first["borderColor"].should eq '#b3b3a4'
    end
  end

  describe "GET district_weeks" do
    it "obtains the district weeks" do
      controller = AgendasController.new
      district_weeks = controller.instance_eval{ district_weeks }
      district_weeks.first["id"].should eq 'C001'
      district_weeks.first["title"].should eq 'Semana distrital'
      district_weeks.first["start"].should eq '2014-03-24'
      district_weeks.first["end"].should eq '2014-03-28'
      district_weeks.first["chamber"].should eq 'C.Diputados'
      district_weeks.first["url"].should eq 'http://www.camara.cl/camara/distritos.aspx'
      district_weeks.first["date_scraped"].should eq '2014-03-22'
    end
  end

  describe "GET show" do
    # [todo] - improve tests
    xit "assigns the requested table as @agenda" do
      table = Table.create! valid_attributes
      get :show, {:id => table.to_param}, valid_session
      assigns(:agenda).should eq(table)
    end
  end

  describe "GET new" do
    xit "assigns a new table as @agenda" do
      get :new, {}, valid_session
      assigns(:agenda).should be_a_new(Table)
    end
  end

  describe "GET edit" do
    xit "assigns the requested table as @agenda" do
      table = Table.create! valid_attributes
      get :edit, {:id => table.to_param}, valid_session
      assigns(:agenda).should eq(table)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      xit "creates a new Table" do
        expect {
          post :create, {:agenda => valid_attributes}, valid_session
        }.to change(Table, :count).by(1)
      end

      xit "assigns a newly created table as @agenda" do
        post :create, {:agenda => valid_attributes}, valid_session
        assigns(:agenda).should be_a(Table)
        assigns(:agenda).should be_persisted
      end

      xit "redirects to the created table" do
        post :create, {:agenda => valid_attributes}, valid_session
        response.should redirect_to(Table.last)
      end
    end

    describe "with invalid params" do
      xit "assigns a newly created but unsaved table as @agenda" do
        # Trigger the behavior that occurs when invalid params are submitted
        Table.any_instance.stub(:save).and_return(false)
        post :create, {:agenda => {  }}, valid_session
        assigns(:agenda).should be_a_new(Table)
      end

      xit "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Table.any_instance.stub(:save).and_return(false)
        post :create, {:agenda => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      xit "updates the requested table" do
        table = Table.create! valid_attributes
        # Assuming there are no other tables in the database, this
        # specifies that the Table created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Table.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => table.to_param, :agenda => { "these" => "params" }}, valid_session
      end

      xit "assigns the requested table as @agenda" do
        table = Table.create! valid_attributes
        put :update, {:id => table.to_param, :agenda => valid_attributes}, valid_session
        assigns(:agenda).should eq(table)
      end

      xit "redirects to the table" do
        table = Table.create! valid_attributes
        put :update, {:id => table.to_param, :agenda => valid_attributes}, valid_session
        response.should redirect_to(table)
      end
    end

    describe "with invalid params" do
      xit "assigns the table as @agenda" do
        table = Table.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Table.any_instance.stub(:save).and_return(false)
        put :update, {:id => table.to_param, :agenda => {  }}, valid_session
        assigns(:agenda).should eq(table)
      end

      xit "re-renders the 'edit' template" do
        table = Table.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Table.any_instance.stub(:save).and_return(false)
        put :update, {:id => table.to_param, :agenda => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    xit "destroys the requested table" do
      table = Table.create! valid_attributes
      expect {
        delete :destroy, {:id => table.to_param}, valid_session
      }.to change(Table, :count).by(-1)
    end

    xit "redirects to the tables list" do
      table = Table.create! valid_attributes
      delete :destroy, {:id => table.to_param}, valid_session
      response.should redirect_to(tables_url)
    end
  end

end
