require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserSubscriptionsController do

  # This should return the minimal set of attributes required to create a valid
  # UserSubscription. As you add validations to UserSubscription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "3" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserSubscriptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    xit "assigns all user_subscriptions as @user_subscriptions" do
      user_subscription = UserSubscription.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_subscriptions).should eq([user_subscription])
    end
  end

  describe "GET show" do
    xit "assigns the requested user_subscription as @user_subscription" do
      user_subscription = UserSubscription.create! valid_attributes
      get :show, {:id => user_subscription.to_param}, valid_session
      assigns(:user_subscription).should eq(user_subscription)
    end
  end

  describe "GET new" do
    xit "assigns a new user_subscription as @user_subscription" do
      get :new, {}, valid_session
      assigns(:user_subscription).should be_a_new(UserSubscription)
    end
  end

  describe "GET edit" do
    xit "assigns the requested user_subscription as @user_subscription" do
      user_subscription = UserSubscription.create! valid_attributes
      get :edit, {:id => user_subscription.to_param}, valid_session
      assigns(:user_subscription).should eq(user_subscription)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      xit "creates a new subscription with a new user" do
        @user_subscription2 = FactoryGirl.build(:user_subscription2)
        expect {
          post :create, :user_subscription => @user_subscription2
        }.to change(UserSubscription, :count).by(1)
      end
      xit "creates a new subscription with an old user" do
      
      end
      xit "creates a subscription that is already in the database" do

      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      xit "updates the requested user_subscription" do
        user_subscription = UserSubscription.create! valid_attributes
        # Assuming there are no other user_subscriptions in the database, this
        # specifies that the UserSubscription created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserSubscription.any_instance.should_receive(:update).with({ "user" => "1" })
        put :update, {:id => user_subscription.to_param, :user_subscription => { "user" => "1" }}, valid_session
      end

      xit "assigns the requested user_subscription as @user_subscription" do
        user_subscription = UserSubscription.create! valid_attributes
        put :update, {:id => user_subscription.to_param, :user_subscription => valid_attributes}, valid_session
        assigns(:user_subscription).should eq(user_subscription)
      end

      xit "redirects to the user_subscription" do
        user_subscription = UserSubscription.create! valid_attributes
        put :update, {:id => user_subscription.to_param, :user_subscription => valid_attributes}, valid_session
        response.should redirect_to(user_subscription)
      end
    end

    describe "with invalid params" do
      xit "assigns the user_subscription as @user_subscription" do
        user_subscription = UserSubscription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserSubscription.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_subscription.to_param, :user_subscription => { "user" => "invalid value" }}, valid_session
        assigns(:user_subscription).should eq(user_subscription)
      end

      xit "re-renders the 'edit' template" do
        user_subscription = UserSubscription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserSubscription.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_subscription.to_param, :user_subscription => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    xit "destroys the requested user_subscription" do
      user_subscription = UserSubscription.create! valid_attributes
      expect {
        delete :destroy, {:id => user_subscription.to_param}, valid_session
      }.to change(UserSubscription, :count).by(-1)
    end

    xit "redirects to the user_subscriptions list" do
      user_subscription = UserSubscription.create! valid_attributes
      delete :destroy, {:id => user_subscription.to_param}, valid_session
      response.should redirect_to(user_subscriptions_url)
    end
  end

end
